Profile: GMTilknyttetJordemodercenterOrganization
Id: GMTilknyttetJordemodercenterOrganization
Parent: GMBaseOrganization

Profile: GMOensketJordemodercenterOrganization
Id: GMOensketJordemodercenterOrganization
Parent: GMBaseOrganization
